/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:7e9fb5e7-7b20-469a-9299-7e5e1bdb3a42",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_L5q7E84Pf",
    "aws_user_pools_web_client_id": "787of1mvnud6te65cfbrhna12i",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "renomerchant1473a3425f274a0698cb7a01af9830cd102526-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;
